version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-blueocean
    user: root
    ports:
      - "8082:8080"  # Mapping port 8082 on host to 8080 in the container
    volumes:
      - jenkins-data:/var/jenkins_home  # Persist Jenkins data
      - "${HOME}:/home"  # Use the full path to your home directory
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Jenkins to communicate with Docker
    restart: always  # Ensures the container restarts automatically

volumes:
  jenkins-data:
    driver: local
